const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const rules=require('../wall-reference-rules'),html=fs.readFileSync('index.html','utf8');
function setup(){
 const nodes=new Map(),handlers={};let fail=false,stored,matchChanges=0,previewIssue='';
 class Element{constructor(id){Object.assign(this,{id,value:'',textContent:'',innerHTML:'',checked:false,disabled:false,style:{},handlers:{},scrollLeft:0,scrollTop:0,scrollWidth:2000,scrollHeight:1000,clientWidth:500,clientHeight:250});nodes.set(id,this);}addEventListener(type,fn){(this.handlers[type]||=[]).push(fn);}async emit(type,extra={}){const e={target:this,detail:1,preventDefault(){this.prevented=true;},stopImmediatePropagation(){this.stopped=true;},...extra};for(const fn of this.handlers[type]||[]){await fn(e);if(e.stopped)break;}return e;}querySelectorAll(){return [...nodes.values()];}setAttribute(){}removeAttribute(name){delete this[name];}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){const v=nodes.get(this.id.replace('Stage','Viewport')),scale=parseFloat(this.style.width)/100||1;return {left:-(v?.scrollLeft||0),top:-(v?.scrollTop||0),width:1000*scale,height:500*scale};}focus(){this.focused=true;}scrollIntoView(){}}
 for(const m of html.matchAll(/\bid="([^"]+)"/g))new Element(m[1]);
 const initialPoints=[[5,5],[95,5],[95,95],[5,95]].map((p,i)=>({id:'p'+i,from:p,to:p,enabled:true,conflict:false,origin:'manual'}));initialPoints.push({id:'bad',from:[30,30],to:[60,5],enabled:true,conflict:true,origin:'automatic'});
 stored={id:'test',label:'Wall section',url:'/api/wall-references/test/image',width:1000,height:500,rotation:0,enabled:true,revision:1,regions:[],alignment:{engine:'wall-align-1',status:'review',inliers:4,points:initialPoints}};
 const calls=[];const save=async(record,result,apply)=>{calls.push({record:structuredClone(record),result:structuredClone(result),apply});if(fail)throw Error('Synthetic interrupted save');assert.equal(record.revision,stored.revision);stored={...record,revision:record.revision+1,alignment:{...record.alignment,...result},regions:apply?result.regions:record.regions};return structuredClone(stored);};
 const window={ImagePan:require('../image-pan'),WallReferenceRules:rules,confirm:()=>true,addEventListener(){},WallMatches:{changed(){matchChanges++;}},WallAlignment:{async preview(record,photos,points){const valid=!previewIssue&&points?.filter(p=>p.enabled).length>=4;return {status:valid?'aligned':'review',method:'reviewed',points:structuredClone(points||initialPoints),regions:valid?[{photoId:'wall1',crop:[10,20,30,40]}]:[],inliers:valid?4:0,reason:previewIssue||'Add four points'};},saveReviewed:(record,result)=>save(record,result,true),saveReviewDraft:(record,points)=>save(record,{status:'review',method:'reviewed',points},false)}};
 const document={getElementById:id=>nodes.get(id),addEventListener(type,fn){(handlers[type]||=[]).push(fn);}};
 vm.runInNewContext(fs.readFileSync('wall-alignment-review.js','utf8'),{window,document,structuredClone,crypto:require('node:crypto').webcrypto});
 return {window,n:id=>nodes.get(id),calls,get stored(){return stored;},get matchChanges(){return matchChanges;},setFail(value){fail=value;},setPreviewIssue(value){previewIssue=value;},async open(){await window.WallAlignmentReview.open(stored,[{id:'wall1',rect:[10,20,30,40]}],'data:image/jpeg;base64,synthetic');},async click(action,id){const target={closest:s=>s==='[data-alignment-'+action+']'?{dataset:{['alignment'+action[0].toUpperCase()+action.slice(1)]:id}}:null};for(const fn of handlers.click||[])await fn({target});}};
}
test('exclude, undo, save for later, reload and apply survive failures without claiming success',async()=>{
 const s=setup();await s.open();assert.match(s.n('alignmentPointSummary').textContent,/1 flagged/);assert.equal(s.n('alignmentApply').disabled,true);
 await s.n('alignmentExcludeConflicts').emit('click');assert.match(s.n('alignmentPointSummary').textContent,/1 excluded/);
 await s.n('alignmentUndo').emit('click');assert.match(s.n('alignmentPointSummary').textContent,/0 excluded/);
 await s.n('alignmentExcludeConflicts').emit('click');await s.n('alignmentSavePoints').emit('click');assert.equal(s.stored.alignment.points.find(p=>p.id==='bad').enabled,false);
 await s.n('alignmentClose').emit('click');await s.open();assert.match(s.n('alignmentPointSummary').textContent,/1 excluded/);
 await s.n('alignmentCheck').emit('click');assert.equal(s.n('alignmentApply').disabled,false);assert.match(s.n('alignmentOriginalCrops').innerHTML,/10%/);assert.match(s.n('alignmentMappedCrops').innerHTML,/<b>1/);
 s.setFail(true);await s.n('alignmentApply').emit('click');assert.equal(s.n('alignmentReviewDialog').open,true);assert.match(s.n('alignmentReviewStatus').textContent,/edits are still here/);assert.equal(s.stored.regions.length,0);
 s.setFail(false);await s.n('alignmentApply').emit('click');assert.equal(s.n('alignmentReviewDialog').open,false);assert.equal(s.stored.regions.length,1);assert.equal(s.matchChanges,2);
});
test('manual pairs use relative coordinates, can be replaced or removed, and editing invalidates preview',async()=>{
 const s=setup();await s.open();await s.n('alignmentClearPoints').emit('click');await s.n('alignmentAddPoint').emit('click');await s.n('alignmentFromStage').emit('click',{clientX:100,clientY:100});await s.n('alignmentToStage').emit('click',{clientX:300,clientY:200});
 await s.n('alignmentSavePoints').emit('click');const pair=s.stored.alignment.points[0];assert.deepEqual(Array.from(pair.from),[10,20]);assert.deepEqual(Array.from(pair.to),[30,40]);
 await s.click('replace',pair.id);await s.n('alignmentFromStage').emit('click',{clientX:200,clientY:100});await s.n('alignmentToStage').emit('click',{clientX:400,clientY:200});await s.n('alignmentSavePoints').emit('click');assert.equal(s.stored.alignment.points.length,1);assert.deepEqual(Array.from(s.stored.alignment.points[0].from),[20,20]);
 await s.n('alignmentCheck').emit('click');assert.equal(s.n('alignmentApply').disabled,true);await s.click('remove',pair.id);await s.n('alignmentSavePoints').emit('click');assert.equal(s.stored.alignment.points.length,0);
 await s.n('alignmentAddCoordinates').emit('click');assert.match(s.n('alignmentReviewStatus').textContent,/all four/);
});

test('suggested repair skips conflicts, advances to a preview without saving, and can be undone',async()=>{
 const s=setup();await s.open();assert.equal(s.n('alignmentStart').hidden,false);assert.equal(s.n('alignmentPhotoWorkspace').hidden,true);assert.equal(s.n('alignmentApply').hidden,true);
 await s.n('alignmentQuickRepair').emit('click');assert.equal(s.n('alignmentStart').hidden,true);assert.equal(s.n('alignmentFinish').hidden,false);assert.equal(s.n('alignmentApply').hidden,false);assert.equal(s.n('alignmentFromPoints').innerHTML,'');assert.equal(s.calls.length,0);assert.equal(s.stored.alignment.points.find(p=>p.id==='bad').enabled,true);
 await s.n('alignmentAdjust').emit('click');await s.n('alignmentUndo').emit('click');assert.match(s.n('alignmentPointSummary').textContent,/1 flagged/);assert.equal(s.n('alignmentApply').disabled,true);assert.equal(s.n('alignmentRepair').hidden,false);
});

test('guided conflict repair shows a labeled pair, preserves it on cancel and replaces it only after both taps',async()=>{
 const s=setup();await s.open();await s.n('alignmentGuidedReview').emit('click');assert.match(s.n('alignmentFocusTitle').textContent,/Point 5.*Possible conflict/);assert.match(s.n('alignmentFromPoints').innerHTML,/! 5/);assert.match(s.n('alignmentFromPoints').innerHTML,/possible conflict/);
 await s.n('alignmentFixSelected').emit('click');assert.equal(s.n('alignmentPlacement').hidden,false);assert.equal(s.n('alignmentCheck').disabled,true);await s.n('alignmentFromStage').emit('click',{clientX:150,clientY:100});assert.match(s.n('alignmentPlacementHelp').textContent,/Second tap/);
 await s.n('alignmentCancelPoint').emit('click');await s.n('alignmentSavePoints').emit('click');assert.deepEqual(s.stored.alignment.points.find(p=>p.id==='bad').from,[30,30]);
 await s.n('alignmentFixSelected').emit('click');await s.n('alignmentFromStage').emit('click',{clientX:150,clientY:100});await s.n('alignmentToStage').emit('click',{clientX:250,clientY:150});assert.match(s.n('alignmentFocusTitle').textContent,/Point 5.*In use/);assert.doesNotMatch(s.n('alignmentFromPoints').innerHTML,/! 5/);await s.n('alignmentSavePoints').emit('click');assert.deepEqual(Array.from(s.stored.alignment.points.find(p=>p.id==='bad').from),[15,20]);
 await s.n('alignmentSkipSelected').emit('click');await s.click('view','bad');assert.match(s.n('alignmentFromPoints').innerHTML,/× 5/);assert.match(s.n('alignmentFocusTitle').textContent,/Skipped/);
});

test('too few corners and failed fits keep the review open with specific correction advice',async()=>{
 const s=setup();s.stored.alignment.points=s.stored.alignment.points.slice(0,2);await s.open();await s.n('alignmentQuickRepair').emit('click');assert.equal(s.n('alignmentRepair').hidden,false);assert.equal(s.n('alignmentCheck').disabled,true);assert.match(s.n('alignmentTroubleAdvice').textContent,/Add 2 more pairs/);assert.equal(s.calls.length,0);
 const t=setup();await t.open();await t.n('alignmentGuidedReview').emit('click');
 for(const [reason,advice] of [['Points along one line cannot align it','upper-left'],['No complete wall picture falls inside these points','whole wall picture'],['The points are still too far apart','inside frame edge'],['Some enabled points still conflict','hidden by glare']]){t.setPreviewIssue(reason);await t.n('alignmentCheck').emit('click');assert.equal(t.n('alignmentRepair').hidden,false);assert.equal(t.n('alignmentFinish').hidden,true);assert.equal(t.n('alignmentApply').disabled,true);assert(t.n('alignmentTroubleAdvice').textContent.includes(advice));}
 assert.match(html,/Red · Possible conflict/);assert.match(html,/Blue · In use/);assert.match(html,/Gray · Skipped/);assert.match(html,/Gold · Your focus or preview/);assert.match(html,/does not mean the person is incorrectly identified/);
});

test('panning either zoomed alignment photo never places a point; the next tap uses the scrolled image coordinates',async()=>{
 const s=setup();await s.open();await s.n('alignmentClearPoints').emit('click');await s.n('alignmentAddPoint').emit('click');
 async function pan(side){const v=s.n('alignment'+side+'Viewport'),stage=s.n('alignment'+side+'Stage');stage.style.width='200%';await v.emit('pointerdown',{pointerType:'touch',pointerId:1,clientX:200,clientY:200});await v.emit('pointerdown',{pointerType:'touch',pointerId:2,clientX:300,clientY:200});await v.emit('pointermove',{pointerType:'touch',pointerId:1,clientX:100,clientY:100});await v.emit('pointermove',{pointerType:'touch',pointerId:2,clientX:200,clientY:100});await v.emit('pointerup',{pointerType:'touch',pointerId:1});await v.emit('pointerup',{pointerType:'touch',pointerId:2});const click=await v.emit('click');assert.equal(click.stopped,true);assert.equal(v.scrollLeft,100);assert.equal(v.scrollTop,100);}
 async function tap(side,x,y){const v=s.n('alignment'+side+'Viewport');await v.emit('pointerdown',{pointerType:'touch',pointerId:3,clientX:x,clientY:y});await v.emit('pointerup',{pointerType:'touch',pointerId:3,clientX:x,clientY:y});assert.equal((await v.emit('click')).stopped,undefined);await s.n('alignment'+side+'Stage').emit('click',{clientX:x,clientY:y});}
 await pan('From');assert.match(s.n('alignmentPlacementHelp').textContent,/First tap/);await tap('From',200,100);assert.match(s.n('alignmentPlacementHelp').textContent,/Second tap/);await pan('To');assert.match(s.n('alignmentPlacementHelp').textContent,/Second tap/);await tap('To',300,200);await s.n('alignmentSavePoints').emit('click');assert.deepEqual(Array.from(s.stored.alignment.points[0].from),[15,20]);assert.deepEqual(Array.from(s.stored.alignment.points[0].to),[20,30]);
});
